Comment out cluster restart which is causing a double restart cycle of pf_ring, cluster and applications (e.g. nprobe)

diff --git a/kernel/pfring-dkms-mkdeb/debian/postinst b/kernel/pfring-dkms-mkdeb/debian/postinst
--- a/kernel/pfring-dkms-mkdeb/debian/postinst
+++ b/kernel/pfring-dkms-mkdeb/debian/postinst
@@ -31,11 +31,15 @@ service_restart () {
 	if hash deb-systemd-invoke 2>/dev/null; then
 		deb-systemd-invoke enable pf_ring > /dev/null
 		deb-systemd-invoke restart pf_ring || echo "Failure restarting pf_ring"
-		deb-systemd-invoke restart cluster || echo "Failure restarting cluster"
+		# Cluster restart is commented out as it causes a second full restart cycle (pf_ring and applications)
+		# Note: cluster is restarted anyway as it depends on pf_ring
+		# deb-systemd-invoke restart cluster || echo "Failure restarting cluster"
 	elif hash systemctl 2>/dev/null; then
 		systemctl enable pf_ring > /dev/null
 		systemctl restart pf_ring || echo "Failure restarting pf_ring"
-		systemctl restart cluster || echo "Failure restarting cluster"
+		# Cluster restart is commented out as it causes a second full restart cycle (pf_ring and applications)
+		# Note: cluster is restarted anyway as it depends on pf_ring
+		# systemctl restart cluster || echo "Failure restarting cluster"
 	else
 		update-rc.d pf_ring defaults 30 >/dev/null
 		update-rc.d cluster defaults 40 >/dev/null
